### PR TITLE
#2 Deduplicate query patterns

### PR DESCRIPTION
**Pull request by mediabakery**

### CODE REVIEW

**Comment by riichard** [comment]
Hey Sebastian, thanks for your time and Pull Request. 

I think your solution works, only it's not as elegant by matching the duplicates by string. It could result to problems with queries containing commas, which confuses with the concatenated array to a comma separated string.

Could you rewrite your solution to a function that compares the two arrays by iterating over it's content? I think it's a fun excercise. 

I had a second function in mind that returns true/false when 2 arrays in random order are equal. This will help to write the deduplicateOr in a simple matter. But I'll leave the implementation completely up to you :)

**Comment by mediabakery** [comment]
Hey Richard,
about your second function in mind. In some cases the order matters, for example:
`true && 'foo'`
I think this is an exceptional case. Maybe we can pass an additional optional parameter for the function, which determines if order matters.

**Comment by mediabakery** [comment]
I agree we should order the array by default. In my PR I added an additional optional parameter `orderMatters`. By default it is **false** and so the arrays will be sorted.

But if the user explicit does not want to sort the array they add a **true** to the function.
See https://github.com/riichard/boolean-parser-js/pull/7/commits/45584cd614fd661434466ba4b96d50dc2cb29bfb#diff-c1129c8b045390789fa8ff62f2c6b4a9R159

**Comment by christensson** [comment]
@riichard: Could you please publish a new version containing these changes to npm?

**Comment by riichard** [comment]
Yes, just published a new release to npm. Enjoy :-)

**Pull request merged**
